apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
  name: rebase-operator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rebase-operator:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/mfojtik/rebase-operator.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fedora:32
        namespace: sttts
    type: Docker
  triggers:
    - github:
        secretReference:
          name: "github-trigger"
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange